version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - app-network

  api:
    build:
      context: ./TestContainers.Api
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__Default=Server=sqlserver;Database=TestContainersDb;User=sa;Password=Your_password123;
    ports:
      - "5000:8080"
    depends_on:
      - sqlserver
    networks:
      - app-network

  web:
    build:
      context: ./TestContainers.Web
      dockerfile: Dockerfile
    environment:
      - ApiBaseUrl=http://api:8080
    ports:
      - "5001:8080"
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:
